name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 16.x

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: 🔨 Installing
        run: yarn install
      - name: ✨ Linting
        run: yarn lint
      - name: 🚜 Building
        run: yarn build
        env:
          # Put your environment variables here
          NODE_ENV: production
          GOOGLE_ANALYTICS_ID: UA-1111111-1
          SITE_URL: http://localhost:8000
      # This is the default configuration that would deploy to gh_pages
      # Check the configuration here https://github.com/peaceiris/actions-gh-pages
      - name: 🚢 Deploying to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./public
          keep_files: true
          # GitHub Actions runner automatically creates a GITHUB_TOKEN secret to use in your workflow.
          github_token: ${{ secrets.GITHUB_TOKEN }}
          #
          # If you want to push to another respository other than this one
          # personal_token: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
          # external_repository: vote4hk/wars.vote4.hk
          #
          # If you want to host with your custom domain
          # cname: [YOUR_DOMAIN]
