name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 14.x

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - run: yarn lint
    - run: yarn build
      env:
        # Put your environment variables here
        NODE_ENV: production
    # This is the default configuration that would deploy to gh_pages 
    # Check the configuration here https://github.com/peaceiris/actions-gh-pages
    - name: Deploy to Github Page
      uses: peaceiris/actions-gh-pages@v3
      with:      
        publish_dir: ./public
        keep_files: true
        # GitHub Actions runner automatically creates a GITHUB_TOKEN secret to use in your workflow. 
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # 
        # If you want to push to another respository other than this one
        # personal_token: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
        # external_repository: vote4hk/wars.vote4.hk
        # 
        # If you want to host with your custom domain 
        # cname: [YOUR_DOMAIN]
   